backend:
  name: git-gateway
  branch: develop
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "locations"
    label: "Locations"
    folder: "src/content/locations"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "location"

      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Image"
        name: "image"
        widget: "image"

      - label: "Category"
        name: "category"
        widget: "categories"

      - label: "Dietary"
        name: "dietary"
        widget: "select"
        multiple: true
        required: false
        options:
          - label: "Vegetarian"
            value: vegetarian
          - label: "Vegan"
            value: vegan
          - label: "Halal"
            value: halal
          - label: "Gluten Free"
            value: gluten_free
          - label: "Healthy"
            value: healthy

      - label: "Links"
        name: "links"
        widget: "list"
        collapsed: false
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
          - label: "Category"
            name: "category"
            widget: "select"
            options:
              - label: "Order"
                value: "order"
              - label: "Support"
                value: "support"
          - label: "Link"
            name: "link"
            widget: "string"
          - label: "Type"
            name: "type"
            widget: "select"
            default: "external"
            options:
              - label: "External / Other"
                value: external
              - label: "Deliveroo"
                value: deliveroo
              - label: "Uber Eats"
                value: uber_eats
              - label: "Just Eat"
                value: just_eat
              - label: "Donation"
                value: donation
              - label: "Voucher"
                value: voucher
              - label: "Email"
                value: email
              - label: "Phone"
                value: phone

      - label: "Location"
        name: "location"
        widget: "places"

      - label: "Do Gooder"
        name: "do_gooder"
        widget: "string"
        required: false
