backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "locations"
    label: "Locations"
    folder: "src/content/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "location"

      - label: "Name"
        name: "name"
        widget: "string"

      - label: "Image"
        name: "image"
        widget: "image"

      - label: "Email"
        name: "email"
        widget: "string"

      - label: "Telephone"
        name: "telephone"
        widget: "string"

      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          - healthy
          - burger
          - breakfast

      - label: "Links"
        name: "links"
        widget: "list"
        collapsed: false
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
          - label: "Type"
            name: "type"
            widget: "select"
            default: "external"
            options:
              - label: "External / Other"
                value: external
              - label: "Deliveroo"
                value: deliveroo
              - label: "Uber Eats"
                value: uber_eats
              - label: "Donation"
                value: donation
              - label: "Voucher"
                value: voucher

      - label: "Location"
        name: "location"
        widget: "places"
